server:
  port: 8083

spring:
  application:
    name: service-consumer
  cloud:
    loadbalancer:
      ribbon:
        enabled: false  # 禁用 Ribbon，Spring Cloud LoadBalancer 替代它
    feign:
      client:
        config:
          default:
            loggerLevel: FULL  # 配置Feign日志，便于查看请求

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: consumer-8083
    prefer-ip-address: true


