#eureka
server:
  port: 8085

spring:
  application:
    name: service-provider  # 服务名称

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: provider-8085
    prefer-ip-address: true



